/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.karenaraujo.projetoloja.view;

import br.com.karenaraujo.projetoloja.controller.EnderecoController;
import br.com.karenaraujo.projetoloja.model.Funcionario;
import br.com.karenaraujo.projetoloja.controller.FuncionarioController;
import br.com.karenaraujo.projetoloja.model.Endereco;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezio_joao
 */
public class CadastrarFuncionarioGUI extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private int linhaSelecionada;

    public CadastrarFuncionarioGUI(DefaultTableModel modelo) {

        this.modelo = modelo;
        initComponents();

    }

    CadastrarFuncionarioGUI(DefaultTableModel modelo, int linhaselecionada, int idFuncionario) {

        this.modelo = modelo;
        this.linhaSelecionada = linhaselecionada;
        initComponents();

        FuncionarioController fc = new FuncionarioController();
        Funcionario u = fc.listarId(idFuncionario);
        ctCodigo.setText(String.valueOf(u.getCodigo()));
        ctNome.setText(u.getNome());
        ctCpf.setText(u.getCpf());
        ctRg.setText(u.getRg());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
        String data = sdf.format(u.getDatanascimento());      
        ctLogin.setText(u.getLogin());
        ctSenha.setText(u.getSenha());
        ctSalario.setText(String.valueOf(u.getSalario()));
        ctTelefone.setText(u.getTelefone());
        ctCargo.setText(u.getCargo());
        ctRua.setText(u.getEndereco().getRua());
        ctBairro.setText(u.getEndereco().getBairro());
        ctCidade.setText(u.getEndereco().getCidade());
        ctNumero.setText(String.valueOf(u.getEndereco().getNumero()));
        ctCep.setText(u.getEndereco().getCep());






    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbSexo = new javax.swing.ButtonGroup();
        PainelFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ctCodigo = new javax.swing.JTextField();
        ctNome = new javax.swing.JTextField();
        ctCpf = new javax.swing.JTextField();
        brFeminino = new javax.swing.JRadioButton();
        brMasculino = new javax.swing.JRadioButton();
        ctRg = new javax.swing.JTextField();
        ctDatanascimento = new javax.swing.JTextField();
        ctLogin = new javax.swing.JTextField();
        ctSenha = new javax.swing.JTextField();
        ctTelefone = new javax.swing.JTextField();
        btSavar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ctSalario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ctCargo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ctRua = new javax.swing.JTextField();
        ctBairro = new javax.swing.JTextField();
        ctCidade = new javax.swing.JTextField();
        ctNumero = new javax.swing.JTextField();
        ctCep = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelFundo.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("RG:");

        jLabel5.setText("Data Nascimento:");

        jLabel6.setText("Login:");

        jLabel7.setText("Senha:");

        jLabel8.setText("Telefone:");

        jLabel9.setText("Sexo:");

        ctCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctCpf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gbSexo.add(brFeminino);
        brFeminino.setText("Feminino");

        gbSexo.add(brMasculino);
        brMasculino.setText("Masculino");

        ctRg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctDatanascimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ctTelefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btSavar.setBackground(new java.awt.Color(51, 255, 255));
        btSavar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6547.png"))); // NOI18N
        btSavar.setText("Salvar");
        btSavar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSavarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(51, 255, 255));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jLabel10.setText("Salário:");

        jLabel11.setText("Cargo:");

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel12.setText("Rua:");

        jLabel13.setText("Bairro:");

        jLabel14.setText("Cidade:");

        jLabel15.setText("Número:");

        jLabel16.setText("CEP:");

        jLabel17.setText("Endereço:");

        ctRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctRuaActionPerformed(evt);
            }
        });

        ctBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctBairroActionPerformed(evt);
            }
        });

        ctCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCidadeActionPerformed(evt);
            }
        });

        ctNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNumeroActionPerformed(evt);
            }
        });

        ctCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelFundoLayout.createSequentialGroup()
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctNome)
                                    .addGroup(PainelFundoLayout.createSequentialGroup()
                                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ctSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                                        .addComponent(ctCpf)
                                                        .addComponent(ctRg, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(ctSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39)
                                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PainelFundoLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(brFeminino)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(brMasculino))
                                                    .addGroup(PainelFundoLayout.createSequentialGroup()
                                                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel11))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(ctTelefone)
                                                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                                                .addComponent(ctDatanascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                                                .addGap(65, 65, 65))
                                                            .addComponent(ctCargo))))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel17))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PainelFundoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctCep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)))
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSavar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar)
                        .addGap(240, 240, 240))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(ctCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brFeminino)
                    .addComponent(brMasculino))
                .addGap(18, 18, 18)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctDatanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ctSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ctCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ctSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13))
                            .addGroup(PainelFundoLayout.createSequentialGroup()
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(ctNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(ctCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSavar)
                            .addComponent(btLimpar))
                        .addGap(18, 18, 18))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ctRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSavarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSavarActionPerformed

        Endereco en = new Endereco();
        en.setRua(ctRua.getText());
        en.setBairro(ctBairro.getText());
        en.setCidade(ctCidade.getText());
        en.setNumero(Integer.parseInt(ctNumero.getText()));
        en.setCep(ctCep.getText());
        EnderecoController ec = new EnderecoController();
        en.setCodigo(ec.salvar(en));

        Funcionario f = new Funcionario();
        if (!(ctCodigo.getText().equals("")) || (ctCodigo.getText().equals(null))) {
            f.setCodigo(Integer.parseInt(ctCodigo.getText()));

        }
        f.setEndereco(en);
        f.setNome(ctNome.getText());
        f.setCpf(ctCpf.getText());
        f.setRg(ctRg.getText());
        f.setLogin(ctLogin.getText());
        f.setSenha(ctSenha.getText());
        f.setTelefone(ctTelefone.getText());
        if (brFeminino.isSelected()) {
            f.setSexo("Feminino");
        } else if (brMasculino.isSelected()) {
            f.setSexo("Masculino");
        }
        f.setSalario(Double.parseDouble(ctSalario.getText()));
        f.setCargo(ctCargo.getText());
        try {
            String data = ctDatanascimento.getText();
            f.setDatanascimento(new SimpleDateFormat("dd/mm/yyyy").parse(data));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao converter a data");
        }
        FuncionarioController fc = new FuncionarioController();

        if (f.getCodigo() == 0) {
            int id = fc.salvar(f);
            modelo.addRow(new Object[]{id, f.getNome(), f.getCpf(), f.getRg(), f.getLogin(), f.getDatanascimento()});
            JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso");

        } else {
            int id = fc.salvar(f);
            if (id > 0) {
                 modelo.removeRow(linhaSelecionada);
                modelo.addRow(new Object[]{id, f.getNome(), f.getCpf(), f.getRg(), f.getLogin(), f.getDatanascimento()});
                JOptionPane.showMessageDialog(null, "Funcionario editado com sucesso");

            }

        }
        dispose();
    }//GEN-LAST:event_btSavarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        ctCodigo.setText("");
        ctNome.setText("");
        ctCpf.setText("");
        ctRg.setText("");
        ctLogin.setText("");
        ctSenha.setText("");
        ctTelefone.setText("");
        gbSexo.clearSelection();
        ctSalario.setText("");
        ctCargo.setText("");
        ctDatanascimento.setText("");
        ctRua.setText("");
        ctBairro.setText("");
        ctCidade.setText("");
        ctNumero.setText("");
        ctCep.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void ctBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctBairroActionPerformed

    private void ctCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCidadeActionPerformed

    private void ctRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctRuaActionPerformed

    private void ctNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNumeroActionPerformed

    private void ctCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCepActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JRadioButton brFeminino;
    private javax.swing.JRadioButton brMasculino;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSavar;
    private javax.swing.JTextField ctBairro;
    private javax.swing.JTextField ctCargo;
    private javax.swing.JTextField ctCep;
    private javax.swing.JTextField ctCidade;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JTextField ctCpf;
    private javax.swing.JTextField ctDatanascimento;
    private javax.swing.JTextField ctLogin;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctNumero;
    private javax.swing.JTextField ctRg;
    private javax.swing.JTextField ctRua;
    private javax.swing.JTextField ctSalario;
    private javax.swing.JTextField ctSenha;
    private javax.swing.JTextField ctTelefone;
    private javax.swing.ButtonGroup gbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
