/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.karenaraujo.projetoloja.view;

import br.com.karenaraujo.projetoloja.controller.CategoriaProdutoController;
import br.com.karenaraujo.projetoloja.controller.FuncionarioController;
import br.com.karenaraujo.projetoloja.controller.ProdutoController;
import br.com.karenaraujo.projetoloja.model.CategoriaProduto;
import br.com.karenaraujo.projetoloja.model.Funcionario;
import br.com.karenaraujo.projetoloja.model.Produto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezio_joao
 */
public class CadastrarProdutoGUI extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;
    private int linhaSelecionada;
    
    public CadastrarProdutoGUI(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
        carregarCombo();
    }
    
    CadastrarProdutoGUI(DefaultTableModel modelo, int linhaselecionada, int idProduto) {
        
        this.modelo = modelo;
        this.linhaSelecionada = linhaselecionada;
        initComponents();
        carregarCombo();
        
        
        ProdutoController pc = new ProdutoController();
        Produto p = pc.listarId(idProduto);
        txCodigo.setText(String.valueOf(p.getCodigo()));
        txNome.setText(p.getNome());
        txqntEstoque.setText(p.getQntEstoque());
        txValor.setText(String.valueOf(p.getValor()));        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(p.getDatafabricacao());
        txData_fabricacao.setText(data);
      
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cxcCategoriapro = new javax.swing.JComboBox();
        txData_fabricacao = new javax.swing.JTextField();
        txValor = new javax.swing.JTextField();
        txqntEstoque = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txCodigo = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade estoque:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Data Fabricação:");

        jLabel6.setText("Categoria do Produto:");

        cxcCategoriapro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txCodigo.setEditable(false);
        txCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6547.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txqntEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txValor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txData_fabricacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(btSalvar)
                                .addGap(43, 43, 43)
                                .addComponent(btLimpar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cxcCategoriapro, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txqntEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txData_fabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxcCategoriapro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoActionPerformed
    }//GEN-LAST:event_txCodigoActionPerformed
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        Produto p = new Produto();
        p.setNome(txNome.getText());
        p.setQntEstoque(txqntEstoque.getText());
        p.setValor(Double.parseDouble(txValor.getText()));
        p.setCategoriaproduto((CategoriaProduto)cxcCategoriapro.getSelectedItem());
        try {
            String data = txData_fabricacao.getText();
            p.setDatafabricacao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao converter a data");
        }
       
        
        
        
      
        if (!(txCodigo.getText().equals("")) || (txCodigo.getText().equals(null))) {
            p.setCodigo(Integer.parseInt(txCodigo.getText()));
        }
        ProdutoController pc = new ProdutoController();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        if (p.getCodigo() == 0) {
            int id = pc.salvar(p);
            modelo.addRow(new Object[]{id, p.getNome(), p.getQntEstoque(), p.getValor(),sdf.format(p.getDatafabricacao()), p.getCategoriaproduto()});
            JOptionPane.showMessageDialog(null, " Produto cadastrado com sucesso");
            
        } else {
            int id = pc.salvar(p);
            if (id > 0) {
                 modelo.removeRow(linhaSelecionada);
                modelo.addRow(new Object[]{id, p.getNome(), p.getQntEstoque(), p.getValor(), sdf.format(p.getDatafabricacao()), p.getCategoriaproduto()});
                JOptionPane.showMessageDialog(null, "Produto editado com sucesso");
            }
        }
        dispose();
    }//GEN-LAST:event_btSalvarActionPerformed
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txCodigo.setText("");
        txNome.setText("");
        txqntEstoque.setText("");
        txValor.setText("");
        txData_fabricacao.setText("");
        
    }//GEN-LAST:event_btLimparActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cxcCategoriapro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txData_fabricacao;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txValor;
    private javax.swing.JTextField txqntEstoque;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo() {
        
        DefaultComboBoxModel combomodel = (DefaultComboBoxModel) cxcCategoriapro.getModel();
        //Remover todos os itens do combo
        combomodel.removeAllElements();

        //Buscar na base de dados os cursos cadastrados
        List<CategoriaProduto> produtos = new ArrayList<>();
        CategoriaProdutoController cpc = new CategoriaProdutoController();
        produtos = cpc.listarTodos();

        //Preencher o combo com os cursos que estão na lista
        for (int linha = 0; linha < produtos.size(); linha++) {
            CategoriaProduto cp = produtos.get(linha);
            combomodel.addElement(cp);
            
        }
    }
    
    private void carregarCombo(CategoriaProduto catepro) {
        DefaultComboBoxModel combomodel = (DefaultComboBoxModel) cxcCategoriapro.getModel();
        //Remover todos os itens do combo
        combomodel.removeAllElements();

        //Buscar na base de dados os cursos cadastrados
        List<CategoriaProduto> produtos = new ArrayList<>();
        CategoriaProdutoController cpc = new CategoriaProdutoController();
        produtos = cpc.listarTodos();

        //Preencher o combo com os cursos que estão na lista
        for (int linha = 0; linha < produtos.size(); linha++) {
            CategoriaProduto cp = produtos.get(linha);
            combomodel.addElement(cp);
            if (catepro.getCodigo() == cp.getCodigo()) {
                combomodel.setSelectedItem(cp);
            }
        }
    }
}
